# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df9e6352424cc31b2d6d2075067453aec05a2789dd65d1d04227add87f9973683914b026344b8bf117eb2920ddef5aa52639a66100c6d82f78860807d7bbe414

test:
  secret_key_base: 4d7b2b428004961e118fc6f9174ed056222b69054a5861baa75ee7aced846c6e860321fce2458584a3f52d49427e78b08fa8c6ef1ae361c3bb14d062f2c01925

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
